name: Tests

on:
    pull_request: null
    push: null

jobs:
    tests:
        runs-on: ubuntu-latest

        name: Tests
        steps:
            -   uses: actions/checkout@v4

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   uses: "ramsey/composer-install@v1"
            -   run: vendor/bin/phpunit
